ALTER TABLE column_metadata
  ADD COLUMN IF NOT EXISTS is_llm_generated  BOOLEAN   DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS confidence        FLOAT     DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS generated_at      TIMESTAMP DEFAULT NULL;
