"""
Email Service Provider (ESP) domain prompts.

Sub-categories are ESP platforms (mailchimp, klaviyo, hubspot) or general.
Generated by domain-architect skill when this domain is initialized.
"""

DOMAIN_LABEL = "email marketing records and contact lists"

_SUB_MAP: dict[str, str] = {
    # "mailchimp": _MAILCHIMP,
    # "klaviyo": _KLAVIYO,
    # "general": _GENERAL,
}


def get_prompt(sub: str | None = None) -> str:
    return _SUB_MAP.get(sub or "general", "")


def list_subs() -> list[str]:
    return list(_SUB_MAP.keys())
