"""
Sports ticketing domain prompts.

Sub-categories are ticketing platforms or general rules.
Generated by domain-architect skill when this domain is initialized.
"""

DOMAIN_LABEL = "sports and entertainment ticketing records"

_SUB_MAP: dict[str, str] = {
    # "ticketmaster": _TICKETMASTER,
    # "axs": _AXS,
    # "general": _GENERAL,
}


def get_prompt(sub: str | None = None) -> str:
    return _SUB_MAP.get(sub or "general", "")


def list_subs() -> list[str]:
    return list(_SUB_MAP.keys())
